name: Testing stage

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
        types:
            - opened
            - edited
            - synchronize
            - reopened
    workflow_call:

jobs:
    lint:
        name: Testing stage
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
            - name: 'â˜ï¸ Checkout repository'
              uses: actions/checkout@v4.1.1

            - name: 'ğŸ”§ Setup node'
              uses: actions/setup-node@v4.0.1
              with:
                  node-version: 20.12.0

            - name: 'ğŸ”§ Install npm@latest'
              run: npm i -g yarn@latest

            - name: 'ğŸ“¦ install dependencies'
              run: yarn

            - name: 'ğŸ” Lint code'
              run: yarn test --coverage
